name: Zig

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    
    - name: Lint
      run: zig fmt --check ./src/*.zig

    - name: Build
      run: zig build --verbose

    - name: Test
      run: zig build test --verbose
